BASE_DIR = ..
LIBNAME = KERN

include $(BASE_DIR)/makedef/makefile.set

USES_LIBKERN=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
include $(BASE_DIR)/makedef/makefile.test