SRC = kn_basic.cpp
OBJ = $(SRC:.cpp=.o)
CXX = g++
# use this to include header files in different directories
INCLUDES = 
LIBS =
# use -std=c++11 => c++11, -Wall => all warnings enabled
CXXFLAGS = -std=c++11 -Wall
NAME = testprog

# Make all object files. A main has not be made as yet.
all: $(OBJ)

include ../makedef/makefile.rules