BASE_DIR = ../..
LIBNAME = GP

include $(BASE_DIR)/makedef/makefile.set

USES_LIBGP=1
USES_LIBCUDP=1
HAS_TESTPROGS=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
