#no test yet
BASE_DIR = ../..

include $(BASE_DIR)/makedef/makefile.set

IS_TESTPROG=1
#TEST_NAME=wanker
#add -l lib names here
USES_LIBKERN=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules