BASE_DIR = ../..

include $(BASE_DIR)/makedef/makefile.set

IS_TESTPROG=1
#creating test program name with ccp file in this directory
TEST_NAME = simple

LIBS += -lboost_timer -lboost_chrono -lboost_system

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
