#MAKESETTINGS - identifier variable of this makefile
MAKESETTINGS=1
#CXX = arm-linux-gnueabihf-g++
CXX = g++
CXXFLAGS = -std=c++11 -Wall
SRC = $(wildcard *.cpp)

#avoid repetition of library object files in this directory for a library
OBJ = $(SRC:.cpp=.o)

INCLUDES =