BASE_DIR = ../../../..

include $(BASE_DIR)/makedef/makefile.set

IS_TESTPROG=1
TEST_NAME=gp_modecontoller
#add -l lib names here
USES_LIBGP=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
