BASE_DIR = ..
LIBNAME = UTILS

include $(BASE_DIR)/makedef/makefile.set

USES_LIBUTILS=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
include $(BASE_DIR)/makedef/makefile.test