BASE_DIR = ../../../..

include $(BASE_DIR)/makedef/makefile.set

IS_TESTPROG=1
TEST_NAME=joystick
#add -l lib names here
USES_LIBJS=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
