BASE_DIR = ..
LIBNAME = COMS

include $(BASE_DIR)/makedef/makefile.set

USES_LIBCOMS=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
include $(BASE_DIR)/makedef/makefile.test