BASE_DIR = ../../../..

include $(BASE_DIR)/makedef/makefile.set

IS_TESTPROG=1
#creating test program name with ccp file in this directory
TEST_NAME = $(SRC:.cpp=) 

USES_LIBDJS=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
