BASE_DIR = ../..
LIBNAME = UTIL_LOGGING

include $(BASE_DIR)/makedef/makefile.set

USES_LIBUTILLOGGING=1
#HAS_TESTPROGS=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
