BASE_DIR = ../../..

include $(BASE_DIR)/makedef/makefile.set

#IS_TESTPROG=1
#creating test program name with cpp file in this directory
#TEST_NAME = basestation

USES_LIBCOMS=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
