BASE_DIR = ../..
LIBNAME = WIRINGPI

include $(BASE_DIR)/makedef/makefile.set

USES_LIBWIRINGPI=1
HAS_TESTPROGS=1

include $(BASE_DIR)/makedef/makefile.libs
include $(BASE_DIR)/makedef/makefile.rules
